In [1]:
import cv2
import numpy as np

net = cv2.dnn.readNet("yolov3.weights","yolov3.cfg")
classes = []

In [2]:
with open("coco.names","r") as f:
    classes = [line.strip() for line in f.readlines()]
layer_names = net.getLayerNames()
outputlayers = [layer_names[i[0] -1] for i in net.getUnconnectedOutLayers()]
colors = np.random.uniform(0, 255, size=(len(classes), 3))

In [ ]:
   #Load Image
vid = cv2.VideoCapture("obj.mp4")
while(vid.isOpened()):
    ret, img = vid.read()
    img = cv2.resize(img, None, fx=0.4, fy =0.4)
    height, width, channels = img.shape
    # Detecting objects
    blob = cv2.dnn.blobFromImage(img, 0.00392, (416, 416), (0, 0, 0), True, crop=False)

    net.setInput(blob)
    outs = net.forward(outputlayers)

    # Showing informations on the screen
    class_ids = []
    confidences = []
    boxes = []
    for out in outs:
        for detection in out:
            scores = detection[5:]
            class_id = np.argmax(scores)
            confidence = scores[class_id]
            if confidence > 0.5:
                # Object detected
                center_x = int(detection[0] * width)
                center_y = int(detection[1] * height)
                w = int(detection[2] * width)
                h = int(detection[3] * height)

                # Rectangle coordinates
                x = int(center_x - w / 2)
                y = int(center_y - h / 2)

                boxes.append([x, y, w, h])
                confidences.append(float(confidence))
                class_ids.append(class_id)
                    # Non-Max Supression
    indexes = cv2.dnn.NMSBoxes(boxes, confidences, 0.5, 0.4)
    print(indexes)
    font = cv2.FONT_HERSHEY_PLAIN
    for i in range(len(boxes)):
        if i in indexes:
            x, y, w, h = boxes[i]
            label = str(classes[class_ids[i]])
            color = colors[i]
            cv2.rectangle(img, (x, y), (x + w, y + h), color, 2)
            cv2.putText(img, label, (x, y + 30), font, 3, color, 3)


    cv2.imshow("image",img)
    if cv2.waitKey(1) & 0xFF == ord('x'):
            VideoCapture.release()
            cv2.destroyAllWindows()
            break

[[0]
 [4]
 [1]
 [5]
 [6]
 [3]]
[[0]
 [3]
 [4]
 [1]
 [5]
 [2]]
[[0]
 [3]
 [5]
 [4]
 [1]]
[[0]
 [2]
 [5]
 [3]
 [4]]
[[0]
 [2]
 [6]
 [4]
 [1]
 [5]
 [3]]
[[0]
 [2]
 [3]
 [5]
 [1]
 [6]]
[[0]
 [2]
 [4]
 [1]
 [5]
 [7]
 [3]]
[[2]
 [0]
 [4]
 [6]
 [5]
 [1]
 [3]
 [7]]
[[0]
 [6]
 [2]
 [5]
 [4]
 [1]
 [3]]
[[0]
 [5]
 [1]
 [3]
 [4]
 [6]]
[[8]
 [3]
 [0]
 [6]
 [7]
 [2]
 [1]
 [5]]
[[0]
 [3]
 [8]
 [7]
 [6]
 [1]
 [2]
 [5]]
[[0]
 [2]
 [6]
 [3]
 [4]
 [1]]
[[4]
 [1]
 [8]
 [6]
 [7]
 [3]
 [2]]
[[4]
 [1]
 [0]
 [5]
 [6]
 [3]
 [2]
 [9]]
[[1]
 [3]
 [0]
 [4]
 [6]
 [2]]
[[4]
 [1]
 [0]
 [8]
 [7]
 [6]
 [2]
 [3]]
[[0]
 [4]
 [1]
 [8]
 [5]
 [2]
 [6]
 [3]]
[[2]
 [1]
 [3]
 [5]
 [7]
 [4]
 [6]]
[[2]
 [1]
 [3]
 [8]
 [0]
 [6]]
[[2]
 [1]
 [3]
 [0]
 [5]
 [7]
 [8]
 [4]]
[[2]
 [1]
 [3]
 [5]
 [9]
 [4]
 [8]
 [7]]
[[ 2]
 [ 1]
 [ 4]
 [ 6]
 [ 7]
 [10]
 [ 5]
 [ 3]
 [ 9]]
[[1]
 [3]
 [7]
 [2]
 [0]
 [6]
 [9]
 [8]]
[[ 1]
 [ 3]
 [ 0]
 [ 7]
 [10]
 [ 8]
 [ 6]]
[[ 1]
 [ 0]
 [ 3]
 [ 9]
 [ 7]
 [ 6]
 [11]
 [10]]
[[ 1]
 [ 8]
 [ 3]
 [ 6]
 [ 7]
 [ 5]

[[0]
 [1]
 [2]
 [8]
 [5]
 [4]
 [6]
 [7]]
[[0]
 [2]
 [1]
 [5]
 [7]
 [9]
 [4]
 [3]]
[[0]
 [2]
 [1]
 [5]
 [7]
 [3]
 [9]
 [8]]
[[0]
 [2]
 [1]
 [7]
 [6]
 [8]
 [5]]
[[0]
 [2]
 [1]
 [7]
 [6]
 [4]
 [3]
 [5]]
[[0]
 [2]
 [1]
 [6]
 [9]
 [7]
 [4]
 [8]]
[[0]
 [1]
 [2]
 [4]
 [5]
 [6]]
[[0]
 [1]
 [2]
 [5]
 [4]
 [7]
 [3]
 [6]]
[[0]
 [3]
 [1]
 [6]
 [2]
 [9]
 [8]]
[[0]
 [2]
 [1]
 [5]
 [4]
 [8]
 [7]
 [3]]
[[0]
 [3]
 [1]
 [6]
 [2]
 [9]
 [7]
 [8]]
[[0]
 [1]
 [4]
 [3]
 [6]
 [2]]
[[0]
 [1]
 [5]
 [3]
 [6]
 [2]
 [7]]
[[0]
 [2]
 [4]
 [1]
 [5]
 [7]
 [6]
 [3]
 [8]]
[[0]
 [5]
 [2]
 [3]
 [1]
 [6]]
[[0]
 [5]
 [2]
 [1]
 [6]
 [8]
 [3]
 [7]
 [9]]
[[0]
 [3]
 [6]
 [4]
 [2]
 [1]
 [8]]
[[0]
 [3]
 [2]
 [1]]
[[ 0]
 [ 6]
 [ 3]
 [11]
 [12]
 [ 2]
 [ 4]
 [10]
 [ 1]
 [ 9]]
[[ 0]
 [ 4]
 [ 7]
 [ 5]
 [ 1]
 [11]
 [10]]
[[ 0]
 [ 6]
 [ 5]
 [ 7]
 [ 1]
 [11]
 [ 3]
 [10]
 [ 4]]
[[0]
 [4]
 [3]
 [5]
 [7]
 [2]
 [9]
 [8]]
[[ 4]
 [ 0]
 [ 5]
 [ 9]
 [ 6]
 [ 3]
 [ 7]
 [ 2]
 [10]
 [11]
 [12]]
[[ 0]
 [ 3]
 [ 4]
 [ 6]
 [ 5]
 [ 2]
 [12]
 [11]
 [10]
 

[[ 2]
 [ 1]
 [ 0]
 [ 7]
 [ 8]
 [ 5]
 [ 6]
 [ 4]
 [10]]
[[ 2]
 [ 0]
 [ 3]
 [10]
 [ 8]
 [ 6]
 [ 9]
 [ 5]
 [ 7]]
[[ 2]
 [ 3]
 [ 0]
 [ 8]
 [10]
 [ 7]
 [ 5]
 [ 9]
 [ 6]]
[[ 1]
 [ 2]
 [ 0]
 [ 4]
 [ 7]
 [10]
 [ 5]
 [ 8]
 [ 9]]
[[2]
 [3]
 [0]
 [7]
 [9]
 [5]
 [6]
 [8]]
[[2]
 [3]
 [7]
 [9]
 [0]
 [5]
 [8]
 [6]]
[[1]
 [2]
 [6]
 [7]
 [8]
 [0]
 [4]]
[[ 2]
 [ 6]
 [ 3]
 [ 7]
 [ 0]
 [ 5]
 [10]
 [ 4]]
[[2]
 [6]
 [1]
 [7]
 [9]
 [8]
 [4]
 [0]]
[[ 6]
 [ 2]
 [ 1]
 [ 7]
 [ 8]
 [ 4]
 [11]
 [ 0]]
[[4]
 [1]
 [5]
 [0]
 [3]
 [6]]
[[ 1]
 [ 6]
 [ 7]
 [ 5]
 [ 0]
 [ 8]
 [ 3]
 [12]]
[[ 1]
 [ 5]
 [ 3]
 [ 0]
 [ 4]
 [ 6]
 [10]
 [11]]
[[ 2]
 [ 8]
 [ 7]
 [ 0]
 [ 5]
 [10]
 [ 3]
 [ 4]]
[[7]
 [2]
 [1]
 [0]
 [6]
 [4]
 [3]]
[[ 9]
 [ 2]
 [ 1]
 [ 0]
 [ 6]
 [ 8]
 [10]
 [ 5]
 [11]
 [ 7]]
[[ 2]
 [ 7]
 [ 1]
 [ 9]
 [ 8]
 [ 0]
 [ 5]
 [ 4]
 [11]]
[[ 3]
 [ 2]
 [ 8]
 [ 9]
 [10]
 [ 5]
 [ 0]
 [ 7]
 [ 4]]
[[2]
 [9]
 [0]
 [1]
 [8]
 [7]
 [4]
 [3]
 [6]]
[[0]
 [2]
 [1]
 [9]
 [6]
 [3]
 [7]
 [4]
 [5]]
[[ 0]
 [10]
 [ 2]
 [ 7]
 [ 9]
 [ 5]
 [ 8]
 [ 4

[[0]
 [1]
 [4]
 [3]
 [6]
 [7]
 [9]
 [8]]
[[0]
 [2]
 [5]
 [6]
 [4]
 [8]]
[[0]
 [2]
 [8]
 [6]
 [5]
 [4]
 [9]
 [7]]
[[0]
 [2]
 [6]
 [9]
 [4]
 [8]
 [7]
 [5]]
[[ 0]
 [ 2]
 [ 5]
 [ 4]
 [ 7]
 [ 8]
 [ 6]
 [10]
 [ 9]]
[[5]
 [0]
 [2]
 [4]
 [7]
 [6]]
[[0]
 [2]
 [5]
 [4]
 [7]
 [6]
 [8]]
[[0]
 [2]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[0]
 [1]
 [3]
 [6]
 [4]
 [5]
 [7]]
[[0]
 [4]
 [1]
 [5]
 [6]]
[[0]
 [4]
 [2]
 [5]
 [7]
 [6]]
[[0]
 [2]
 [4]
 [6]
 [5]
 [7]]
[[0]
 [2]
 [3]
 [4]
 [5]
 [7]
 [6]]
[[0]
 [2]
 [3]
 [4]
 [6]
 [7]]
[[0]
 [2]
 [3]
 [4]
 [6]
 [5]]
[[0]
 [1]
 [4]
 [6]
 [3]
 [5]
 [8]
 [7]]
[[0]
 [1]
 [7]
 [3]
 [5]
 [4]
 [6]]
[[0]
 [3]
 [2]
 [5]
 [8]
 [4]
 [6]
 [9]
 [7]]
[[0]
 [5]
 [4]
 [3]
 [7]
 [1]]
[[0]
 [3]
 [2]
 [4]
 [7]
 [1]
 [6]]
[[0]
 [2]
 [4]
 [5]
 [3]
 [1]]
[[0]
 [1]
 [3]
 [2]
 [5]]
[[0]
 [2]
 [8]
 [6]
 [3]
 [5]
 [7]]
[[0]
 [1]
 [2]
 [5]
 [4]
 [3]
 [6]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [7]
 [5]
 [8]
 [6]]
[[0]
 [1]
 [2]
 [5]
 [6]
 [3]
 [4]]
[[0]
 [3]
 [1]
 [6]
 [5]
 [4]
 [7]]
[[0]
 [6]
 [3]
 [5]
 [4]
 [1]