In [1]:
import cv2
import numpy as np

net = cv2.dnn.readNet("yolov3.weights","yolov3.cfg")
classes = []

In [2]:
with open("coco.names","r") as f:
    classes = [line.strip() for line in f.readlines()]
layer_names = net.getLayerNames()
outputlayers = [layer_names[i[0] -1] for i in net.getUnconnectedOutLayers()]
colors = np.random.uniform(0, 255, size=(len(classes), 3))

In [5]:
   #Load Image
vid = cv2.VideoCapture("obj.mp4")
while(vid.isOpened()):
    ret, img = vid.read()
    frame = img
    img = cv2.resize(img, None, fx=0.4, fy =0.4)
    height, width, channels = img.shape
    # Detecting objects
    blob = cv2.dnn.blobFromImage(img, 0.00392, (416, 416), (0, 0, 0), True, crop=False)

    net.setInput(blob)
    outs = net.forward(outputlayers)
    
    # Showing informations on the screen
    class_ids = []
    confidences = []
    boxes = []
    centroids = []
    for out in outs:
        for detection in out:
            scores = detection[5:]
            class_id = np.argmax(scores)
            confidence = scores[class_id]
            if confidence > 0.5:
                # Object detected
                center_x = int(detection[0] * width)
                center_y = int(detection[1] * height)

                w = int(detection[2] * width)
                h = int(detection[3] * height)

                # Rectangle coordinates
                x = int(center_x - w / 2)
                y = int(center_y - h / 2)

                boxes.append([x, y, w, h])
                confidences.append(float(confidence))
                class_ids.append(class_id)
     # Non-Max Supression
    indexes = cv2.dnn.NMSBoxes(boxes, confidences, 0.5, 0.4)
    print(indexes)
    font = cv2.FONT_HERSHEY_PLAIN
    for i in range(len(boxes)):
        if i in indexes:
            x, y, w, h = boxes[i]
            label = str(classes[class_ids[i]])
            color = colors[i]
            cv2.rectangle(img, (x, y), (x + w, y + h), color, 2)
            cv2.putText(img, label, (x, y + 30), font, 3, color, 3)


    cv2.imshow("image",img)
    if cv2.waitKey(1) & 0xFF == ord('x'):
            VideoCapture.release()
            cv2.destroyAllWindows()
            break

[[208]
 [  3]]
[[208]
 [  3]]
[[208]
 [  3]]
[[0]
 [4]
 [1]
 [5]
 [6]
 [3]]
[[209]
 [  3]]
[[209]
 [  3]]
[[209]
 [  3]]
[[0]
 [3]
 [4]
 [1]
 [5]
 [2]]
[[206]
 [  3]]
[[206]
 [  3]]
[[206]
 [  3]]
[[0]
 [3]
 [5]
 [4]
 [1]]
[[208]
 [  1]]
[[208]
 [  1]]
[[208]
 [  1]]
[[0]
 [2]
 [5]
 [3]
 [4]]
[[208]
 [  1]]
[[208]
 [  1]]
[[208]
 [  1]]
[[0]
 [2]
 [6]
 [4]
 [1]
 [5]
 [3]]
[[209]
 [  3]]
[[209]
 [  3]]
[[209]
 [  3]]
[[0]
 [2]
 [3]
 [5]
 [1]
 [6]]
[[209]
 [  3]]
[[209]
 [  3]]
[[209]
 [  3]]
[[0]
 [2]
 [4]
 [1]
 [5]
 [7]
 [3]]
[[209]
 [  1]]
[[209]
 [  1]]
[[209]
 [  1]]
[[2]
 [0]
 [4]
 [6]
 [5]
 [1]
 [3]
 [7]]
[[209]
 [  1]]
[[209]
 [  1]]
[[209]
 [  1]]
[[0]
 [6]
 [2]
 [5]
 [4]
 [1]
 [3]]
[[211]
 [  3]]
[[211]
 [  3]]
[[211]
 [  3]]
[[0]
 [5]
 [1]
 [3]
 [4]
 [6]]
[[211]
 [  5]]
[[211]
 [  5]]
[[211]
 [  5]]
[[8]
 [3]
 [0]
 [6]
 [7]
 [2]
 [1]
 [5]]
[[211]
 [  2]]
[[211]
 [  2]]
[[211]
 [  2]]
[[0]
 [3]
 [8]
 [7]
 [6]
 [1]
 [2]
 [5]]
[[211]
 [  4]]
[[211]
 [  4]]
[[211]
 [  4]]
[[0]
 [2

KeyboardInterrupt: 